default:
  # Absolute path to batches data files.
  batches: C:/Users/jean-/OneDrive/Documents/Adhesion/data/batch/raw
  
  # Absolute path to the created concatenate file
  concatenate_file: C:/Users/jean-/OneDrive/Documents/Adhesion/data/batch/concatenate/data_concatenate.csv
  
  # Absolute path to the created concatenate id file
  concatenate_id_file: C:/Users/jean-/OneDrive/Documents/Adhesion/data/batch/concatenate/id_concatenate.csv
  
  # Absolute path to the created corrected id file
  corrected_id_file: C:/Users/jean-/OneDrive/Documents/Adhesion/data/batch/corrected/id_corrected.csv
  
  # Absolute path to the created directory containing one file by id
  data_curve: C:/Users/jean-/OneDrive/Documents/Adhesion/data/batch/data_by_id_corrected
  
  # List (comma separated, no space) of accepted comment
  comment_accepted: ok,0s,5min
  
  # Absolute path to the created directory containing one file by index result
  index_path:  C:/Users/jean-/OneDrive/Documents/Adhesion/data/index
  
  # Absolute path to the created directory containing the plots (load_time)
  plot_path:  C:/Users/jean-/OneDrive/Documents/Adhesion/data/plot
  
  # Absolute path to the created directory containing the integral files
  integral_path:  C:/Users/jean-/OneDrive/Documents/Adhesion/data/integral
  
