default:
  # Absolute path to batches data files.
  batches: C:/Users/jean-/OneDrive/Documents/Adhesion/data/batch/raw
  
  # Absolute path to the created concatenate file
  concatenate_file: C:/Users/jean-/OneDrive/Documents/Adhesion/data/batch/concatenate/data_concatenate.csv
  
  # Absolute path to the created concatenate id file
  concatenate_id_file: C:/Users/jean-/OneDrive/Documents/Adhesion/data/batch/concatenate/id_concatenate.csv
  
  # Absolute path to metadata files. The first 15 columns must have exactly the same name. If a 16th column is present, it contains the protocol
  metadata: C:/Users/jean-/OneDrive/Documents/Adhesion/data/metadata/raw
  
  # Absolute path to the created concatenate metadata fileconcatenate_file
  concatenate_metadata: C:/Users/jean-/OneDrive/Documents/Adhesion/data/metadata/metadata_concatenate.csv
  
  # Absolute path to the created directory containing one file by id
  batch_by_id: C:/Users/jean-/OneDrive/Documents/Adhesion/data/batch/batch_by_id
  
  # List (comma separated, no space) of accepted comment
  # comment_accepted: ok
  comment_accepted: ok,not_detached, cuticle_broke
  
  # List (comma separated, no space) of accepted protocol
  protocol_accepted: 0s,5min,default
  
  # Absolute path to the created directory containing one file by index result
  index_path:  C:/Users/jean-/OneDrive/Documents/Adhesion/data/index/index.csv
  
  # Absolute path to the created directory containing the plots (load_time)
  plot_path:  C:/Users/jean-/OneDrive/Documents/Adhesion/data/plot
  
  # Absolute path to the created directory containing the integral files
  integral_path:  C:/Users/jean-/OneDrive/Documents/Adhesion/data/integral
  
  # Absolute path to the created directory containing the imageJ files
  imagej_path:  C:/Users/jean-/OneDrive/Documents/Adhesion/data/imageJ/raw
  
  # Raw parameter names
  parameter_list: detachment_force, energy, negative_energy, rigidity, position_difference, pression_extension, pupa_area, pupa_length, Glue_area, log10_detachment_force, log10_energy, log10_negative_energy, log10_rigidity, log10_position_difference, log10_pupa_area, log10_pupa_length, log10_glue_area
  
  # Pretty parameter names (must be in same order as parameter_list)
  lab_list: Detachment force, Short term energy, Proxy of long term energy,Rigidity, Position difference, Pression extension, Pupa area, Pupa length, Glue area, log10(Detachment force), log10(Short term energy), log10(Proxy of long term energy), log10(Rigidity), log10(Position difference), log10(Pression extention) , log10(Pupa area), log10(Pupa length), log10(Glue area)
  
  # Unit of each parameter (must be in same order as parameter_list)
  unit_list: Newton, N.mm, N.mm, N.mm-1, mm, mm, mm^2, mm, um^2, Newton, N.mm, N.mm, N.mm-1, mm, mm^2, mm, um^2

  # Stat (R function name) to perform
  stat_list: mean, max, min, median, sd
  
portable:
  # Absolute path to batches data files.
  batches: C:\Users\jean-noel.lorenzi\/Documents/Adhesion/data/batch/raw
  
  # Absolute path to the created concatenate file
  concatenate_file: C:/Users/jean-noel.lorenzi/Documents/Adhesion/data/batch/concatenate/data_concatenate.csv
  
  # Absolute path to the created concatenate id file
  concatenate_id_file: C:/Users/jean-noel.lorenzi/Documents/Adhesion/data/batch/concatenate/id_concatenate.csv
  
  # Absolute path to metadata files. The first 15 columns must have exactly the same name. If a 16th column is present, it contains the protocol
  metadata: C:/Users/jean-noel.lorenzi/Documents/Adhesion/data/metadata/raw
  
  # Absolute path to the created concatenate metadata fileconcatenate_file
  concatenate_metadata: C:/Users/jean-noel.lorenzi/Documents/Adhesion/data/metadata/metadata_concatenate.csv
  
  # Absolute path to the created directory containing one file by id
  batch_by_id: C:/Users/jean-noel.lorenzi/Documents/Adhesion/data/batch/batch_by_id
  
  # List (comma separated, no space) of accepted comment
  # comment_accepted: ok
  comment_accepted: ok,not_detached, cuticle_broke
  
  # List (comma separated, no space) of accepted protocol
  protocol_accepted: 0s,5min,default
  
  # Absolute path to the created directory containing one file by index result
  index_path:  C:/Users/jean-noel.lorenzi/Documents/Adhesion/data/index/index.csv
  
  # Absolute path to the created directory containing the plots (load_time)
  plot_path:  C:/Users/jean-noel.lorenzi/Documents/Adhesion/data/plot
  
  # Absolute path to the created directory containing the integral files
  integral_path:  C:/Users/jean-noel.lorenzi/Documents/Adhesion/data/integral
  
  # Absolute path to the created directory containing the imageJ files
  imagej_path:  C:/Users/jean-noel.lorenzi/Documents/Adhesion/data/imageJ/raw
   
manon_acanthoptera:
  # Absolute path to batches data files
  batches: /perso/monier/Documents/Adhesion_test_data/Integrales/Jean_Noel_22_03_23/data/batch/raw

  # Absolute path to the created concatenate file
  concatenate_file: /perso/monier/Documents/Adhesion_test_data/Integrales/Jean_Noel_22_03_23/data/batch/concatenate/data_concatenate.csv

  # Absolute path to the created concatenate id file
  concatenate_id_file: /perso/monier/Documents/Adhesion_test_data/Integrales/Jean_Noel_22_03_23/data/batch/concatenate/id_concatenate.csv

  # Absolute path to metadata files. The first 15 columns must have exactly the same name. If a 16th column is present, it contains the protocol
  metadata: /perso/monier/Documents/Adhesion_test_data/Integrales/Jean_Noel_22_03_23/data/metadata/raw

  # Absolute path to the created concatenate metadata fileconcatenate_file
  concatenate_metadata: /perso/monier/Documents/Adhesion_test_data/Integrales/Jean_Noel_22_03_23/data/metadata/metadata_concatenate.csv

  # Absolute path to the created directory containing one file by id
  batch_by_id: /perso/monier/Documents/Adhesion_test_data/Integrales/Jean_Noel_22_03_23/data/batch/batch_by_id

  # List (comma separated, no space) of accepted comment
  # comment_accepted: ok
  comment_accepted: ok,not_detached, cuticle_broke

  # List (comma separated, no space) of accepted protocol
  protocol_accepted: 0s,5min,default

  # Absolute path to the created directory containing one file by index result
  index_path:  /perso/monier/Documents/Adhesion_test_data/Integrales/Jean_Noel_22_03_23/data/index/index.csv

  # Absolute path to the created directory containing the plots (load_time)
  plot_path:  /perso/monier/Documents/Adhesion_test_data/Integrales/Jean_Noel_22_03_23/data/plot

  # Absolute path to the created directory containing the integral files
  integral_path:  /perso/monier/Documents/Adhesion_test_data/Integrales/Jean_Noel_22_03_23/data/integral

  # Absolute path to the created directory containing the imageJ files
  imagej_path:  /perso/monier/Documents/Adhesion_test_data/Integrales/Jean_Noel_22_03_23/data/imageJ/raw
